version: '3.8'
services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_NAME: demo5
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 731224
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 731224
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

volumes:
  postgres_data:

